services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shorturl'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  redis: